// commitlint + cz-git（git-cz 交互式提交）共用配置
// 提交类型只允许下面这些，scope 与项目目录结构对应
module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
        'i18n',
      ],
    ],
    'subject-max-length': [2, 'always', 72],
    'body-max-line-length': [2, 'always', 100],
  },
  prompt: {
    useEmoji: false,
    themeColorCode: '',
    messages: {
      type: '选择提交类型（必填）:',
      scope: '选择影响范围（可选，可跳过）:',
      customScope: '自定义影响范围:',
      subject: '简短描述（必填，≤72 字，句末不加句号）:',
      body: '补充说明（可选，每行 ≤100 字）:',
      breaking: '是否是不兼容变更（BREAKING CHANGE）:',
      footerPrefixsSelect: '选择关联 issue 类型（可选）:',
      customFooterPrefixs: '自定义前缀:',
      footer: '关联的 issue，如 #12:',
      confirmCommit: '确认提交？',
    },
    types: [
      { value: 'feat', name: 'feat:     新功能' },
      { value: 'fix', name: 'fix:      修复缺陷' },
      { value: 'i18n', name: 'i18n:     国际化（文案 / 双语字段 / 语言包）' },
      { value: 'refactor', name: 'refactor: 重构（不改变外部行为）' },
      { value: 'perf', name: 'perf:     性能优化' },
      { value: 'test', name: 'test:     测试' },
      { value: 'docs', name: 'docs:     文档' },
      { value: 'style', name: 'style:    代码风格（不影响逻辑）' },
      { value: 'build', name: 'build:    构建 / 依赖' },
      { value: 'ci', name: 'ci:       CI 配置' },
      { value: 'chore', name: 'chore:    其他杂项' },
      { value: 'revert', name: 'revert:   回滚提交' },
    ],
    scopes: [
      'web',
      'server',
      'ontology',
      'mapping',
      'extraction',
      'graph',
      'evidence',
      'semantics',
      'catalog',
      'i18n',
      'deps',
    ],
    allowCustomScopes: true,
    allowEmptyScopes: true,
    skipQuestions: ['breaking', 'footerPrefixsSelect', 'customFooterPrefixs', 'footer'],
    subjectComplete: true,
  },
}
