"""initial schema

Revision ID: 67ccedb5a0e9
Revises: None
Create Date: 2026-09-21 15:12:27.222718
"""

from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '67ccedb5a0e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assembly_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('basis', sa.Text(), nullable=False),
    sa.Column('builtin', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('iri', sa.String(length=640), nullable=False),
    sa.Column('label_i18n', sa.JSON(), nullable=True),
    sa.Column('definition_i18n', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='resourcestatus'), nullable=False),
    sa.Column('current_revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_domain_name')
    )
    op.create_table('canvas_layout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('positions', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'owner_id', name='uq_canvas_per_scope')
    )
    op.create_table('datasource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('credential_cipher', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_datasource_name')
    )
    op.create_table('namespace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prefix', sa.String(length=64), nullable=False),
    sa.Column('iri', sa.String(length=512), nullable=False),
    sa.Column('protected', sa.Boolean(), nullable=False),
    sa.Column('label_i18n', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iri'),
    sa.UniqueConstraint('prefix')
    )
    op.create_table('validation_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('target_revision', sa.Integer(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domain_revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['business_domain.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id', 'revision')
    )
    op.create_table('metadata_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datasource_id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('catalog', sa.JSON(), nullable=False),
    sa.Column('diff', sa.JSON(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['datasource_id'], ['datasource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('ENTITY', 'DATATYPE_PROP', 'OBJECT_PROP', 'ASSOC', 'NAMESPACE', 'DOMAIN', 'ONTOLOGY', name='resourcekind'), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('iri', sa.String(length=640), nullable=False),
    sa.Column('namespace_id', sa.Integer(), nullable=False),
    sa.Column('label_i18n', sa.JSON(), nullable=True),
    sa.Column('definition_i18n', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='resourcestatus'), nullable=False),
    sa.Column('current_revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['namespace_id'], ['namespace.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iri', name='uq_resource_iri'),
    sa.UniqueConstraint('name', name='uq_resource_name')
    )
    op.create_index('ix_resource_kind', 'model_resource', ['kind'], unique=False)
    op.create_index('ix_resource_status', 'model_resource', ['status'], unique=False)
    op.create_table('ontology',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('iri', sa.String(length=640), nullable=False),
    sa.Column('label_i18n', sa.JSON(), nullable=True),
    sa.Column('definition_i18n', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='resourcestatus'), nullable=False),
    sa.Column('current_revision', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['assembly_template.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_ontology_name')
    )
    op.create_table('validation_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('check_code', sa.String(length=64), nullable=False),
    sa.Column('state', sa.Enum('PASS', 'VIOLATION', 'NA', 'NOT_RUN', name='validationstate'), nullable=False),
    sa.Column('focus_node', sa.String(length=640), nullable=True),
    sa.Column('rule_id', sa.String(length=128), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['validation_report.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'check_code', name='uq_result_per_check')
    )
    op.create_table('domain_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('as_ref', sa.Boolean(), nullable=False),
    sa.Column('owner_domain_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['business_domain.id'], ),
    sa.ForeignKeyConstraint(['owner_domain_id'], ['business_domain.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['model_resource.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id', 'resource_id', 'as_ref', name='uq_domain_member')
    )
    op.create_table('mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('ontology_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='resourcestatus'), nullable=False),
    sa.Column('current_revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ontology_id'], ['ontology.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_mapping_name')
    )
    op.create_table('ontology_resource_ref',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ontology_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('pinned_revision', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ontology_id'], ['ontology.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['model_resource.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ontology_id', 'resource_id', name='uq_onto_resource_ref')
    )
    op.create_table('ontology_revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ontology_id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('ref_domains', sa.JSON(), nullable=False),
    sa.Column('ref_types', sa.JSON(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('resource_versions', sa.JSON(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ontology_id'], ['ontology.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ontology_id', 'revision')
    )
    op.create_table('resource_parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['model_resource.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['model_resource.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id', 'parent_id', name='uq_parent_link')
    )
    op.create_table('resource_ref',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['model_resource.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['model_resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ref_source', 'resource_ref', ['source_id'], unique=False)
    op.create_index('ix_ref_target', 'resource_ref', ['target_id'], unique=False)
    op.create_table('resource_revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['model_resource.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', 'revision', name='uq_revision_per_resource')
    )
    op.create_table('mapping_revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mapping_id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('onto_version', sa.Integer(), nullable=False),
    sa.Column('entity_maps', sa.JSON(), nullable=False),
    sa.Column('rel_maps', sa.JSON(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['mapping_id'], ['mapping.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mapping_id', 'revision')
    )
    op.create_table('extraction_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mapping_revision_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'PARTIAL', 'FAILED', 'CANCELLED', name='runresult'), nullable=False),
    sa.Column('cfg_snapshot', sa.JSON(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('counts', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mapping_revision_id'], ['mapping_revision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mapping_preview',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mapping_revision_id', sa.Integer(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['mapping_revision_id'], ['mapping_revision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graph_revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('publishable', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['extraction_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_graph_current', 'graph_revision', ['is_current'], unique=False)
    op.create_table('quarantine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=128), nullable=False),
    sa.Column('row_key', sa.String(length=256), nullable=False),
    sa.Column('field', sa.String(length=128), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('transform_chain', sa.JSON(), nullable=False),
    sa.Column('rule_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['extraction_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('derived_edge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('graph_revision_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=640), nullable=False),
    sa.Column('predicate', sa.String(length=640), nullable=False),
    sa.Column('object', sa.String(length=640), nullable=False),
    sa.ForeignKeyConstraint(['graph_revision_id'], ['graph_revision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_identity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('graph_revision_id', sa.Integer(), nullable=False),
    sa.Column('iri', sa.String(length=640), nullable=False),
    sa.Column('type_iri', sa.String(length=640), nullable=False),
    sa.Column('row_key', sa.String(length=256), nullable=False),
    sa.Column('attrs', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['graph_revision_id'], ['graph_revision.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('graph_revision_id', 'iri', name='uq_entity_iri')
    )
    op.create_table('fact_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('graph_revision_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=640), nullable=False),
    sa.Column('predicate', sa.String(length=640), nullable=False),
    sa.Column('object', sa.String(length=640), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=128), nullable=False),
    sa.Column('row_key', sa.String(length=256), nullable=False),
    sa.Column('columns', sa.JSON(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['graph_revision_id'], ['graph_revision.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['extraction_run.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['datasource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_triple', 'fact_evidence', ['subject', 'predicate', 'object'], unique=False)
    op.create_table('graph_triple',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('graph_revision_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=640), nullable=False),
    sa.Column('predicate', sa.String(length=640), nullable=False),
    sa.Column('object', sa.String(length=640), nullable=False),
    sa.ForeignKeyConstraint(['graph_revision_id'], ['graph_revision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_triple_object', 'graph_triple', ['object'], unique=False)
    op.create_index('ix_triple_subject', 'graph_triple', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_triple_subject', table_name='graph_triple')
    op.drop_index('ix_triple_object', table_name='graph_triple')
    op.drop_table('graph_triple')
    op.drop_index('ix_evidence_triple', table_name='fact_evidence')
    op.drop_table('fact_evidence')
    op.drop_table('entity_identity')
    op.drop_table('derived_edge')
    op.drop_table('quarantine')
    op.drop_index('ix_graph_current', table_name='graph_revision')
    op.drop_table('graph_revision')
    op.drop_table('mapping_preview')
    op.drop_table('extraction_run')
    op.drop_table('mapping_revision')
    op.drop_table('resource_revision')
    op.drop_index('ix_ref_target', table_name='resource_ref')
    op.drop_index('ix_ref_source', table_name='resource_ref')
    op.drop_table('resource_ref')
    op.drop_table('resource_parent')
    op.drop_table('ontology_revision')
    op.drop_table('ontology_resource_ref')
    op.drop_table('mapping')
    op.drop_table('domain_member')
    op.drop_table('validation_result')
    op.drop_table('ontology')
    op.drop_index('ix_resource_status', table_name='model_resource')
    op.drop_index('ix_resource_kind', table_name='model_resource')
    op.drop_table('model_resource')
    op.drop_table('metadata_snapshot')
    op.drop_table('domain_revision')
    op.drop_table('validation_report')
    op.drop_table('namespace')
    op.drop_table('datasource')
    op.drop_table('canvas_layout')
    op.drop_table('business_domain')
    op.drop_table('assembly_template')
    # ### end Alembic commands ###
